import{s as c,i as a}from"./assets/vendor-5c957d73.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery");function f({webformatURL:r,largeImageURL:i,tags:o,likes:s,views:e,comments:t,downloads:n}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${i}"><img class="list-img" src="${r}" alt="${o}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${t}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${n}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function m(r){return r.map(f).join("")}function p(r){const i=m(r);u.innerHTML=i}function d(r){document.querySelector(".form").insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>');const o=new URLSearchParams({key:"45046577-03496d23e82ad22c3baa8c519",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20});return fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const l={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul")};l.formEl.addEventListener("submit",r=>{r.preventDefault(),l.ul.innerHTML="",l.input.value.trim()?(d(l.input.value.trim()).then(o=>{o.total!==0?(p(o.hits),new c(".gallery a").refresh()):a.error({message:"Image is not found",position:"topRight"})}).catch(o=>{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{document.querySelector(".loader").style.display="none"}),l.input.value=""):a.error({message:"Please fill in the input field",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
